package com.dy.networkdisk.api.config

enum class ConfigInfo(val propKey:String,val redisKey: String,val default: String) {
    //网站标题
    WEB_TITLE(
            "web.title",
            "QYDisk:config:web:title",
            "青叶网盘"
    ),
    //允许注册
    WEB_REGISTER_ALLOW(
            "web.register.allow",
            "QYDisk:config:web:register:allow",
            "true"
    ),
    //注册必须邀请
    WEB_REGISTER_ONLY_INVITE(
            "web.register.onlyInvite",
            "QYDisk:config:web:register:onlyInvite",
            "false"
    ),
    //限制登录(维护)
    WEB_LOGIN_LIMIT(
            "web.login.limit",
            "QYDisk:config:web:login:limit"
            ,"false"
    ),

    //验证码字符集
    WEB_VERIFICATION_CHARSET(
            "web.verification.charset",
            "QYDisk:config:web:verification:charset",
            "0123456789"
    ),
    //验证码失效时间(分钟)
    WEB_VERIFICATION_EXPIRE(
            "web.verification.expire",
            "QYDisk:config:web:verification:expire",
            "10"
    ),
    //验证码长度
    WEB_VERIFICATION_LENGTH(
            "web.verification.length",
            "QYDisk:config:web:verification:length",
            "4"
    ),
    //验证码忽略大小写
    WEB_VERIFICATION_CASE_IGNORE(
            "web.verification.ignoreCase",
            "QYDisk:config:web:verification:ignoreCase",
            "false"
    ),
    //验证码边框
    WEB_VERIFICATION_BORDER(
            "web.verification.border",
            "QYDisk:config:web:verification:border",
            "no"
    ),
    //验证码边框颜色
    WEB_VERIFICATION_BORDER_COLOR(
            "web.verification.border.color",
            "QYDisk:config:web:verification:border:color",
            "black"
    ),
    //验证码边框宽度
    WEB_VERIFICATION_BORDER_WIDTH(
            "web.verification.border.width",
            "QYDisk:config:web:verification:border:width",
            "0"
    ),
    //验证码字体颜色
    WEB_VERIFICATION_FONT_COLOR(
            "web.verification.font.color",
            "QYDisk:config:web:verification:font:color",
            "black"
    ),
    //验证码字体大小
    WEB_VERIFICATION_FONT_SIZE(
            "web.verification.font.size",
            "QYDisk:config:web:verification:font:size",
            "20"
    ),
    //验证码字体间距
    WEB_VERIFICATION_FONT_SPACE(
            "web.verification.font.space",
            "QYDisk:config:web:verification:font:space",
            "5"
    ),
    //验证码干扰实现类
    WEB_VERIFICATION_NOISE_IMPL(
            "web.verification.noise.impl",
            "QYDisk:config:web:verification:noise:impl",
            "com.google.code.kaptcha.impl.NoNoise"
    ),
    //验证码干扰颜色
    WEB_VERIFICATION_NOISE_COLOR(
            "web.verification.noise.color",
            "QYDisk:config:web:verification:noise:color",
            "black"
    ),
    //验证码风格实现类
    WEB_VERIFICATION_STYLE_IMPL(
            "web.verification.style.impl",
            "QYDisk:config:web:verification:style:impl",
            "com.google.code.kaptcha.impl.ShadowGimpy"
    ),
    //验证码背景开始颜色
    WEB_VERIFICATION_BACKGROUND_COLOR_FROM(
            "web.verification.background.color.from",
            "QYDisk:config:web:verification:background:color:from",
            "darkGray"
    ),
    //验证码背景结束颜色
    WEB_VERIFICATION_BACKGROUND_COLOR_TO(
            "web.verification.background.color.to",
            "QYDisk:config:web:verification:background:color:to",
            "gray"
    ),

    //游客信息过期时间(小时)
    USER_GUESTS_EXPIRE(
            "user.guests.expire",
            "QYDisk:config:user:guests:expire",
            "12"
    ),
    //在线会话保存时间(分钟)
    USER_ONLINE_EXPIRE(
            "user.online.expire",
            "QYDisk:config:user:online:expire",
            "30"
    ),
    //自动登录有效期(天)
    USER_AUTOLOGIN_EXPIRE(
            "user.autologin.expire",
            "QYDisk:config:user:autologin:expire",
            "30"
    ),

    //邮件署名
    MAIL_SIGNATURE(
            "mail.signature",
            "QYDisk:config:mail:signature",
            "青叶网盘"
    ),

    //上传任务超时
    UPLOAD_EXPIRE(
            "upload.expire",
            "QYDisk:config:storage:expire",
            "24"
    ),

    //下载缓存
    DOWNLOAD_CACHE_SIZE(
        "download.cache.size",
        "QYDisk:config:storage:cache:size",
        "2"
    )
}
