server:
  port: 8083

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/networkdisk #mysql地址
    username: #mysql用户名
    password: #mysql密码
  redis:
    host: localhost #redis地址
    port: 6379 #redis端口
  activemq:
    broker-url: tcp://localhost:61616 #activeMQ地址
    user: admin #activeMQ用户名
    password: admin #activeMQ密码

mybatis:
  mapper-locations: classpath:/mapper/**.xml

dubbo:
  application:
    name: userModule
  scan:
    base-packages: com.dy.networkdisk.user.service
  protocol:
    name: dubbo
    port: 18083
  registry:
    address: zookeeper://127.0.0.1:2181