server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/networkdisk
  redis:
    host: localhost
    port: 6379
    database: 0

dubbo:
  application:
    name: userMudel
  scan:
    base-packages: com.dy.networkdisk.user.service
  protocol:
    name: dubbo
    port: 18083
  registry:
    address: zookeeper://127.0.0.1:2181