server:
  port: 8182

QYDisk:
  id-worker:
    workerID: 0
  config:
    cache:
      enable: true
      expire: 600000

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/networkdisk
    username: root
    password: QYDisk2020
  redis:
    host: localhost
    port: 6379
  mvc:
    servlet:
      load-on-startup: 1

mybatis:
  mapper-locations: classpath:/mapper/**.xml

dubbo:
  application:
    name: fileModule
  scan:
    base-packages: com.dy.networkdisk.file.service
  protocol:
    name: dubbo
    port: 18182
  registry:
    address: zookeeper://127.0.0.1:2181