server:
  port: 8025

spring:
  mail:
    host: smtp.163.com
    username: QYDisk2020@163.com
    password: QYDisk1235
    port: 25
    protocol: smtp
    default-encoding: UTF-8
  thymeleaf:
    cache: false

dubbo:
  application:
    name: emailModule
  scan:
    base-packages: com.dy.networkdisk.email.service
  protocol:
    name: dubbo
    port: 18025
  registry:
    address: zookeeper://127.0.0.1:2181